services:
  - type: web
    name: n8n
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: DATABASE_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        fromService:
          name: n8n-postgres
          type: pserv
          property: host
      - key: DB_POSTGRESDB_PORT
        value: 5432
      - key: DB_POSTGRESDB_DATABASE
        value: n8n
      - key: DB_POSTGRESDB_USER
        fromService:
          name: n8n-postgres
          type: pserv
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromService:
          name: n8n-postgres
          type: pserv
          property: password
      - key: N8N_ENCRYPTION_KEY
        sync: false # Changed from generateValue to sync so you can set a fixed value
      - key: N8N_PORT
        value: 5678
      - key: WEBHOOK_URL
        sync: false # This allows us to set a custom value during deployment
      - key: GENERIC_TIMEZONE
        value: UTC
      - key: TZ
        value: UTC
      - key: N8N_PERSIST_DATA
        value: true
    disk:
      name: n8n-data
      mountPath: /home/node/.n8n
      sizeGB: 10
    healthCheckPath: /


  - type: pserv
    name: n8n-postgres
    env: docker
    plan: standard
    image:
      name: postgres
      tag: 14
    envVars:
      - key: POSTGRES_USER
        value: n8n
      - key: POSTGRES_PASSWORD
        sync: false # Changed from generateValue to sync for consistency
      - key: POSTGRES_DB
        value: n8n
    disk:
      name: postgres-data
      mountPath: /var/lib/postgresql/data
      sizeGB: 10