services:
  - type: web
    name: n8n
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: DATABASE_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_URL
        sync: false # You'll set your Supabase connection string here
      - key: N8N_ENCRYPTION_KEY
        sync: false # Set a strong encryption key
      - key: N8N_PORT
        value: "5678"
      - key: WEBHOOK_URL
        sync: false # Your n8n webhook URL
      - key: GENERIC_TIMEZONE
        value: UTC
      - key: TZ
        value: UTC
      - key: N8N_PERSIST_DATA
        value: "true"
    disk:
      name: n8n-data
      mountPath: /home/node/.n8n
      sizeGB: 10
    healthCheckPath: /